### ISSUE TITLE
GRDB crashes (EXC_BAD_ACCESS) when setting iOS 18 as min target deployment with XCode 16 RC

### ISSUE THREAD

**Issue by abournier** [groue/GRDB.swift#1619]
Hello,

### What did you do?

I changed my iOS project minimum deployment from iOS 17 to iOS 18.
The app crashes (at app launch) when using dbWriter.

`Thread 1: EXC_BAD_ACCESS (code=1, address=0x28)`

<img width="711" alt="Capture d’écran 2024-09-10 à 20 38 20" src="https://github.com/user-attachments/assets/7804c2dd-3a79-4a23-b225-75a87624d691">

This crash disappears when coming back to iOS 17 min target deployment.
I have no idea why this happens, the dbReader seems to be accessible.

```
// Database initializer
struct AppDatabase {
		
		/// Application can use a `DatabasePool`, while SwiftUI previews and tests can use a fast in-memory `DatabaseQueue`.
		let dbWriter: DatabaseWriter
	
		/// Instantiate a `Database`, and make sure the database schema is ready.
		init(_ dbAccess: DatabaseWriter) throws {
				self.dbWriter = dbAccess
		}
		
		/// Provides a read-only access to the database
		var dbReader: DatabaseReader {
				dbWriter
		}

}
```

### Environment

GRDB 6.29.3
GRDBQuery 0.9.0
XCode 16 RC
Swift 5.x
macOS 14.x

Thanks in advance,

**Comment by groue** [comment]
Hello @abournier,

Thanks for the report. It looks like a duplicate of #1596.

Please report the bug at http://feedbackassistant.apple.com/.

**Comment by abournier** [comment]
Hello groue,

I didn't match the previous issue, sorry.
Well, I will report the bug to Apple too.

However, I just downloaded the GRDBCombineDemo app to test it.
I have a similar issue when targeting iOS 18 min, no issue when targeting iOS 17 min.

<img width="1344" alt="Capture d’écran 2024-09-11 à 09 57 28" src="https://github.com/user-attachments/assets/c52073c1-1929-46c7-ab27-c6cc968e30ae">

**Comment by groue** [comment]
Yes, it looks like the same issue. It would be a great contribution to look for a workaround and share it, if it exists. I am not personally searching for one.

**Comment by abournier** [comment]
Did you crash the GRDBCombineDemo app when targeting iOS 18 min on your Mac too ?

One (maybe) important last thing... I used an Intel Mac (MBP 2018), not an Apple Silicon Mac.

**Comment by abournier** [comment]
As mentioned by @SwiftedMind in #1596, I can confirm that the crash doesn't appear in Xcode 16 beta 1 for:
- my app
- the GRDBCombineDemo app

They both work using iOS 18 as target min at the time.

Maybe Apple has already resolved the issue... I'm not sure there could be a possible workaround with Xcode 16 RC.

**Comment by Jnosh** [comment]
For reference, i also reported this on the Swift repository a while back: https://github.com/swiftlang/swift/issues/76014

**Comment by groue** [comment]
Crash is reproduced at https://github.com/groue/GRDBIssue1619

**Comment by Jnosh** [comment]
Perhaps this is fixed by https://github.com/swiftlang/swift/pull/76383 - the nightly toolchains don't yet work on macOS 15 but if someone has a macOS 14 install around they might be able to test.

**Comment by darioroa** [comment]
Reporting that I still get the crash in Xcode 16.0 RC. I assume this is the only version that can upload builds for the initial iOS 18 launch? If so, it might require adding iOS 17 minimum target.

**Comment by groue** [comment]
The root cause is a [compiler/SDK bug](https://mastodon.sdf.org/@mikeash/113136475433234842) that will be fixed eventually, so there is no reason to modify the library.

A known workaround is to modify the app so that its IPHONEOS_DEPLOYMENT_TARGET is less than 18.0.

Another known workaround is to fork GRDB and modify its Package.swift so that the minimum iOS version is 18. Do as in this commit: https://github.com/groue/GRDB.swift/commit/4c541a99b541caca9d8572641e5e2d98588d36ce. Please do this in your own fork: I do not guarantee that the linked commit will remain accessible in the future.

**Comment by abournier** [comment]
Thanks for the feedback. It's always interesting.

> The root cause of the crash is a [compiler/SDK bug](https://mastodon.sdf.org/@mikeash/113136475433234842) that will be fixed eventually, so there is no reason to modify the library.

As the current version is working properly in XCode 16 Beta 1 (target iOS 18 min), this means something has already been fixed in the SDK no ?

**Comment by groue** [comment]
> As the current version is working properly in XCode 16 Beta 1 (target iOS 18 min), this means something has already been fixed in the last SDK ?

Probably, but I'm not able to tell anything about the compiler version that ships with Xcode. The PR linked above by @Jnosh is quite recent, and looks quite related, so the whole story is not closed.

In my current understanding, it looks like a regular integration of GRDB through SPM is solved in Xcode 16.1 (which is not able to submit apps to the App Store, though). But some people build XCFrameworks (ABI-resilient builds) out of GRDB, and this does not seem solved yet (I can't quite put my finger on the GitHub comment or mastodon post about those frameworks).

**Comment by groue** [comment]
The compiler bug is still present in Xcode 16 (16A242d) 😬

**Comment by Jnosh** [comment]
Also present in Xcode 16.1 Beta 2. Which I guess makes sense since that appears to still be based on the Swift 6.0.0 release.

The PR I linked is only merged for the Swift >6.0.1 branches so hopefully we see an Xcode 16.0.1 at some point in the not too far away future including that or at least functioning toolchains so we can test if this is indeed fixed.

**Comment by groue** [comment]
Thanks for the heads-up, @Jnosh. What a mess.

**Comment by Jnosh** [comment]
I can still reproduce this with the just released Swift 6.0.1 toolchain.

https://forums.swift.org/t/announcing-swift-6-0-1/74940

There doesn't seem to be a branch for Swift 6.0.1 in the Swift repo so I'm not sure if the potential fix didn't make it into 6.0.1 or if it doesn't actually fix this particular issue. But since that change isn't called out in the release notes at all, I'm hoping it's just the former.

(And I still can't get the Swift 6 development toolchain to work to try and verify with that)

**Comment by groue** [comment]
[Confirmed](https://sfba.social/@dgregor79/113200047035251337). Can't tell anything more.

**Comment by SF-Simon** [comment]
> [Confirmed](https://sfba.social/@dgregor79/113200047035251337). Can't tell anything more.

Hello, @groue . Today both macOS and iOS have been updated to 18.0.1, but as expected, the issue still persists. I'm really frustrated with this problem because I need to use some of the new features in iPadOS, but this bug is preventing me from coding with the project. Do you have any suggestions? Should I use that commit (4c541a9) for now? Would that cause me to miss out on future updates to GRDB?

**Comment by groue** [comment]
Yes @SF-Simon. I did not check if the workarounds described above https://github.com/groue/GRDB.swift/issues/1619#issuecomment-2351023394 still work with 18.0.1, but that's the idea. This situation is very frustrating. We know that [some fix exists, and is just not shipped yet](https://sfba.social/@dgregor79/113200047035251337).

**Comment by Jnosh** [comment]
The issue appears to be fixed with Xcode 16.1 beta 3 which is using the Swift 6.0.2 branch. 🎉

I don't know if there will also be an Xcode 16.0.1 with this in it or if we have to wait for Xcode 16.1 but at least the fix seems to work.

**Comment by groue** [comment]
Now that Xcode 16.1 RC is out, let's close this issue :)
