### ISSUE TITLE
Error occur when adding FTS5CustomTokenizer.

### ISSUE THREAD

**Issue by ningkaiqiang** [groue/GRDB.swift#1670]
I have a database that contains texts, I want to add a search feature, So I try to add a custom tokenizer to do this task.
After reading the docs, I try to use FTS5CustomTokenizer to add my custom tokenizer, but there are two error keep happens.

### 1
`"FTS5TokenizerDescriptor requires at least one component"`

The first error occur when **FTS5TokenizerConstructor -> constructor** execute, When this block execute, the arguments is empty, so I added a check to the FTS5CustomTokenizer impl, which is like this one

    init(db: GRDB.Database, arguments: [String] = []) throws {
        wrappedTokenizer = try db.makeTokenizer(
            .init(components: arguments.isEmpty ? ["mecab"] : arguments)
        )
    }

After this, the first error is disappeared, but the other error keep happen.

### 2
`Thread 1: EXC_BAD_ACCESS (code=2, address=0x16d2e7ef4)`

When this error occur, first I think it's some thread safe problem, but after I make the code run in a serial thread, it still happens.
When it happens, there many duplicate call stacks.
Here is a call stack screenshot when the error occur.

<img width="251" alt="image" src="https://github.com/user-attachments/assets/a16db8a3-8db9-4d06-8888-ecf7e934aaa4">
<img width="252" alt="image" src="https://github.com/user-attachments/assets/a8bffc5a-976a-4044-8755-2e6660dab107">

#### The **FTS5CustomTokenizer** impl code

    final class MecabFTS: FTS5CustomTokenizer {
    
        static var name: String = "mecab"
        var wrappedTokenizer: any GRDB.FTS5Tokenizer
    
        init(db: GRDB.Database, arguments: [String] = []) throws {
            wrappedTokenizer = try db.makeTokenizer(
                .init(components: arguments.isEmpty ? ["mecab"] : arguments)
            )
        }
    
        func tokenize(
            context: UnsafeMutableRawPointer?,
            tokenization: GRDB.FTS5Tokenization,
            pText: UnsafePointer<CChar>?,
            nText: CInt,
            tokenCallback: GRDB.FTS5TokenCallback
        ) -> CInt {
            return Tokenizer.fts5(
                context: context,
                pText: pText,
                nText: nText,
                tokenCallback: tokenCallback
            )
        }
    }

#### The table creation

        try db.create(virtualTable: "\(tableName)_FTS", using: FTS5()) { table in
            table.synchronize(withTable: tableName)
            table.tokenizer = MecabFTS.tokenizerDescriptor()
            table.column("id")
            table.column("text")
        }

#### The database configuration

        var config = Configuration()
        
        config.prepareDatabase { [weak self] db in
            db.add(tokenizer: MecabFTS.self)
        }

Is there something I am doing wrong?

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** master(3ecb5c5)
**Installation method:** SPM
**Xcode version:** 16.0
**Swift version:** swift 5.x
**Platform(s) running GRDB:** iOS sim
**macOS version running Xcode:** 15.1

**Comment by groue** [comment]
Hello @ningkaiqiang,

The crash may be #1619, which was fixed in Xcode 16.1. If you can't upgrade Xcode, look for the workarounds described in the issue.

For the `FTS5TokenizerDescriptor` error... I'm not sure what the `wrappedTokenizer` is used for, actually. I would appreciate a fully reproducible example (some code that I just have to paste and run without any modification).

**Comment by ningkaiqiang** [comment]
Hello!! @groue  thanks a lot you for your help. I try to update Xcode to 16.1, The issue does not resolved, then I try to check some tests you wrote. Follow the tests, I modified my `init(db: GRDB.Database, arguments: [String] = []) throws` impl, then it works!!


    init(db: GRDB.Database, arguments: [String] = []) throws {
        if arguments.isEmpty {
            wrappedTokenizer = try db.makeTokenizer(.porter())
        } else {
            wrappedTokenizer = try db.makeTokenizer(FTS5TokenizerDescriptor(components: arguments))
        }
    }

I'll close this issue now.
